services:
  - type: web
    name: discord-twitter-middleware
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: DISCORD_WEBHOOK_URL
        value: https://discord.com/api/webhooks/1369596699823181824/OtGp_hZ14zklWS9F-QBg4YHhEgWyiwYbvJsNlRn--lRPiEUEZOnW06T5t5SrNdalo6Sy